# Generated by Django 5.0.6 on 2026-04-26 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('founded_year', models.IntegerField()),
                ('logo', models.ImageField(upload_to='team/')),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='team.team')),
            ],
            options={
                'verbose_name': 'Таблиця',
                'verbose_name_plural': 'Таблиці',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='team/')),
                ('website', models.URLField(blank=True)),
                ('level', models.CharField(choices=[('gold', 'Золотий'), ('silver', 'Срібний'), ('bronze', 'Бронзовий')], default='bronze', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='team.team')),
            ],
            options={
                'verbose_name': 'Спонсор',
                'verbose_name_plural': 'Спонсори',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Воротар'), ('DEF', 'Захисник'), ('MID', 'Півзахисник'), ('FWD', 'Нападник')], max_length=3)),
                ('number', models.IntegerField()),
                ('photo', models.ImageField(upload_to='players/')),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.team')),
            ],
            options={
                'verbose_name': 'Гравець',
                'verbose_name_plural': 'Гравці',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('team_goals', models.IntegerField(blank=True, null=True)),
                ('opponent_goals', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Майбутній'), ('played', 'Зіграний')], default='upcoming', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='team.team')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчі',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='coaches/')),
                ('bio', models.TextField()),
                ('experience', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='team.team')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренери',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='team.team')),
            ],
            options={
                'verbose_name': 'Пост блогу',
                'verbose_name_plural': 'Пости блогу',
                'ordering': ['-created_at'],
            },
        ),
    ]
