# Generated by Django 5.0.6 on 2026-04-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_match_opponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('GK', 'Воротар'), ('DEF', 'Захисник'), ('MID', 'Півзахисник'), ('FWD', 'Нападник')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Заявка до команди',
                'verbose_name_plural': 'Заявки до команди',
                'ordering': ['-created_at'],
            },
        ),
    ]
