# Generated by Django 5.0.6 on 2026-04-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_blogpost_image_alter_coach_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='display_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
