# Generated by Django 5.0.6 on 2026-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_standing_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('matches', 'Матчі'), ('standings', 'Таблиця'), ('blog', 'Блог'), ('join', 'Приєднатися'), ('sponsors', 'Спонсори')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('background_color', models.CharField(default='#1e3c72', max_length=120)),
                ('primary_button_text', models.CharField(blank=True, max_length=60)),
                ('primary_button_url', models.CharField(blank=True, max_length=200)),
                ('secondary_button_text', models.CharField(blank=True, max_length=60)),
                ('secondary_button_url', models.CharField(blank=True, max_length=200)),
                ('show_logo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Банер сторінки',
                'verbose_name_plural': 'Банери сторінок',
                'ordering': ['page'],
            },
        ),
    ]
