# Generated by Django 5.0.6 on 2026-04-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
