# Generated by Django 5.0.6 on 2026-04-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('about', 'Про нас'), ('matches', 'Матчі'), ('standings', 'Таблиця'), ('blog', 'Блог'), ('join', 'Приєднатися'), ('sponsors', 'Спонсори')], max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='hero_backgrounds/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фон верхнього блоку',
                'verbose_name_plural': 'Фони верхніх блоків',
                'ordering': ['page'],
            },
        ),
    ]
