# Generated by Django 5.0.6 on 2026-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_herobackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Головний візуал', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='home_hero/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Головний візуал',
                'verbose_name_plural': 'Головний візуал',
            },
        ),
    ]
