# Generated by Django 4.2.13 on 2026-05-29 11:11

from django.db import migrations, models


def seed_home_gallery_images(apps, schema_editor):
    HomeGalleryImage = apps.get_model('team', 'HomeGalleryImage')
    images = [
        ('Березань', 'team/c407216a-2974-4ab2-ad0a-2f7933e1ae62.png'),
        ("Зазим'є", 'blog/913ab2b4-889a-4368-9d9a-af8559889b4a.png'),
        ('Команда', 'team/2020_02_02_00_02_32_1580594913.png'),
        ("Зазим'є 2023", 'team/913ab2b4-889a-4368-9d9a-af8559889b4a.png'),
        ("Зазим'є ФК", 'team/913ab2b4-889a-4368-9d9a-af8559889b4a_vNB0aQG.png'),
        ('Юнацький футбол', 'team/480504591_122117371814669800_5307027548570642863_n.jpg'),
        ('Атлант', 'team/271526792_100588375853786_312336484217132342_n.jpg'),
        ('Командне фото', 'team/images.jpeg'),
        ('Емблема', 'team/images_1.jpeg'),
    ]

    for order, (title, image) in enumerate(images, start=1):
        HomeGalleryImage.objects.get_or_create(
            image=image,
            defaults={
                'title': title,
                'order': order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_seed_team_blog_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='home_gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фото життя команди',
                'verbose_name_plural': 'Фото життя команди',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_home_gallery_images, migrations.RunPython.noop),
    ]
