# Generated by Django 4.2.13 on 2026-05-29 13:49

from django.db import migrations, models


def migrate_age_to_birth_year(apps, schema_editor):
    JoinApplication = apps.get_model('team', 'JoinApplication')
    age_to_birth_year = {
        '5': 2021,
        '6': 2020,
        '7': 2019,
        '8': 2018,
    }

    for application in JoinApplication.objects.all():
        application.birth_year = age_to_birth_year.get(application.age, 2018)
        application.save(update_fields=['birth_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_homegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinapplication',
            name='birth_year',
            field=models.PositiveSmallIntegerField(choices=[(2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021')], default=2018),
        ),
        migrations.RunPython(migrate_age_to_birth_year, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='joinapplication',
            name='age',
        ),
    ]
