# Generated by Django 4.2.13 on 2026-06-02 12:43

from django.db import migrations, models


def seed_about_gallery_items(apps, schema_editor):
    AboutGalleryItem = apps.get_model('team', 'AboutGalleryItem')
    items = [
        ('Тренування', 'team/c407216a-2974-4ab2-ad0a-2f7933e1ae62.png'),
        ('Матчі', 'blog/913ab2b4-889a-4368-9d9a-af8559889b4a.png'),
        ('Емоції', 'team/913ab2b4-889a-4368-9d9a-af8559889b4a.png'),
    ]

    for order, (title, image) in enumerate(items, start=1):
        AboutGalleryItem.objects.get_or_create(
            title=title,
            defaults={
                'image': image,
                'order': order,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_remove_joinapplication_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='about_gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фото сторінки Про нас',
                'verbose_name_plural': 'Фото сторінки Про нас',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_about_gallery_items, migrations.RunPython.noop),
    ]
