# Generated by Django 4.2.13 on 2026-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_aboutgalleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Вставте посилання на YouTube, наприклад https://youtu.be/... або https://www.youtube.com/watch?v=...', verbose_name='YouTube відео'),
        ),
    ]
